name: e_commerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # إصدار متوافق مع الجميع

dependencies:
  flutter:
    sdk: flutter

  injectable: ^2.5.0
  get_it: ^8.0.2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  shared_preferences: ^2.2.3
  go_router: ^13.2.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
  connectivity_plus: ^5.0.2
  retrofit: 4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  retrofit_generator: 8.0.6
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
